spring:
  member-profile:
    path: "/imagetest/profiles"
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: xx
      secretKey: xx
    s3:
      bucket: codingtomato
      dir: /hola
    region:
      static: us-west-1
    stack:
      auto: false

