spring:
  member-profile:
    path: "/imagetest/profiles"
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: xx
      secretKey: xx
    s3:
      bucket: xx
      dir: xx
    region:
      static: us-west-1
    stack:
      auto: false