spring:
  profiles:
    group:
      "default": "local"
      "dev": "dev"
      "test": "test"
---
spring:
  profiles:
    active: local

  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:~/codingMates;AUTO_SERVER=true
    url: jdbc:h2:tcp://localhost/~/codingmates;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
        show_sql: true
        #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
        format_sql: true
        #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
        use_sql_comments: true
    defer-datasource-initialization: true
    generate-ddl: true

---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:postgresql://codingmatesdb.c8pa7vtqsrpa.us-west-1.rds.amazonaws.com:5432/coding_mates_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: disneyland77

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
          show_sql: true
          #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
          format_sql: true
          #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
          use_sql_comments: true
      defer-datasource-initialization: true
      generate-ddl: true

---
spring:
  config:
    activate:
      on-profile: "test"
  member-profile:
    path: "/imagetest/profiles"

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
